package data;
// Generated 2017-04-18 21:19:21 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Produkty generated by hbm2java
 */
@Entity
@Table(name="produkty"
    ,catalog="sklep"
)
public class Produkty  implements java.io.Serializable {


     private int idProduktu;
     private Producent producent;
     private Typ typ;
     private int idTyp;
     private int idProducenta;
     private String nazwa;
     private String opis;
     private int cena;
     private Zamowienia zamowienia;

    public Produkty() {
    }

	
    public Produkty(Producent producent, Typ typ, int idTyp, int idProducenta, String nazwa, String opis, int cena) {
        this.producent = producent;
        this.typ = typ;
        this.idTyp = idTyp;
        this.idProducenta = idProducenta;
        this.nazwa = nazwa;
        this.opis = opis;
        this.cena = cena;
    }
    public Produkty(Producent producent, Typ typ, int idTyp, int idProducenta, String nazwa, String opis, int cena, Zamowienia zamowienia) {
       this.producent = producent;
       this.typ = typ;
       this.idTyp = idTyp;
       this.idProducenta = idProducenta;
       this.nazwa = nazwa;
       this.opis = opis;
       this.cena = cena;
       this.zamowienia = zamowienia;
    }
   
     @GenericGenerator(name="generator", strategy="foreign", parameters=@Parameter(name="property", value="producent"))@Id @GeneratedValue(generator="generator")

    
    @Column(name="Id_Produktu", unique=true, nullable=false)
    public int getIdProduktu() {
        return this.idProduktu;
    }
    
    public void setIdProduktu(int idProduktu) {
        this.idProduktu = idProduktu;
    }

@OneToOne(fetch=FetchType.LAZY)@PrimaryKeyJoinColumn
    public Producent getProducent() {
        return this.producent;
    }
    
    public void setProducent(Producent producent) {
        this.producent = producent;
    }

@OneToOne(fetch=FetchType.LAZY)@PrimaryKeyJoinColumn
    public Typ getTyp() {
        return this.typ;
    }
    
    public void setTyp(Typ typ) {
        this.typ = typ;
    }

    
    @Column(name="Id_Typ", nullable=false)
    public int getIdTyp() {
        return this.idTyp;
    }
    
    public void setIdTyp(int idTyp) {
        this.idTyp = idTyp;
    }

    
    @Column(name="Id_Producenta", nullable=false)
    public int getIdProducenta() {
        return this.idProducenta;
    }
    
    public void setIdProducenta(int idProducenta) {
        this.idProducenta = idProducenta;
    }

    
    @Column(name="Nazwa", nullable=false, length=50)
    public String getNazwa() {
        return this.nazwa;
    }
    
    public void setNazwa(String nazwa) {
        this.nazwa = nazwa;
    }

    
    @Column(name="Opis", nullable=false, length=50)
    public String getOpis() {
        return this.opis;
    }
    
    public void setOpis(String opis) {
        this.opis = opis;
    }

    
    @Column(name="Cena", nullable=false)
    public int getCena() {
        return this.cena;
    }
    
    public void setCena(int cena) {
        this.cena = cena;
    }

@OneToOne(fetch=FetchType.LAZY, mappedBy="produkty")
    public Zamowienia getZamowienia() {
        return this.zamowienia;
    }
    
    public void setZamowienia(Zamowienia zamowienia) {
        this.zamowienia = zamowienia;
    }




}


