package data;
// Generated 2017-05-06 18:08:38 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Producent generated by hbm2java
 */
@Entity
@Table(name="producent"
    ,catalog="sklep"
)
public class Producent  implements java.io.Serializable {


     private int idProducenta;
     private String nazwaProducenta;
     private Set<Produkty> produkties = new HashSet<Produkty>(0);

    public Producent() {
    }

	
    public Producent(int idProducenta, String nazwaProducenta) {
        this.idProducenta = idProducenta;
        this.nazwaProducenta = nazwaProducenta;
    }
    public Producent(int idProducenta, String nazwaProducenta, Set<Produkty> produkties) {
       this.idProducenta = idProducenta;
       this.nazwaProducenta = nazwaProducenta;
       this.produkties = produkties;
    }
   
     @Id 

    
    @Column(name="Id_Producenta", unique=true, nullable=false)
    public int getIdProducenta() {
        return this.idProducenta;
    }
    
    public void setIdProducenta(int idProducenta) {
        this.idProducenta = idProducenta;
    }

    
    @Column(name="Nazwa_Producenta", nullable=false, length=50)
    public String getNazwaProducenta() {
        return this.nazwaProducenta;
    }
    
    public void setNazwaProducenta(String nazwaProducenta) {
        this.nazwaProducenta = nazwaProducenta;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="producent")
    public Set<Produkty> getProdukties() {
        return this.produkties;
    }
    
    public void setProdukties(Set<Produkty> produkties) {
        this.produkties = produkties;
    }




}


