package data;
// Generated 2017-04-18 21:19:21 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * Typ generated by hbm2java
 */
@Entity
@Table(name="typ"
    ,catalog="sklep"
)
public class Typ  implements java.io.Serializable {


     private int idTyp;
     private String nazwaTypu;
     private Produkty produkty;

    public Typ() {
    }

	
    public Typ(int idTyp, String nazwaTypu) {
        this.idTyp = idTyp;
        this.nazwaTypu = nazwaTypu;
    }
    public Typ(int idTyp, String nazwaTypu, Produkty produkty) {
       this.idTyp = idTyp;
       this.nazwaTypu = nazwaTypu;
       this.produkty = produkty;
    }
   
     @Id 

    
    @Column(name="Id_Typ", unique=true, nullable=false)
    public int getIdTyp() {
        return this.idTyp;
    }
    
    public void setIdTyp(int idTyp) {
        this.idTyp = idTyp;
    }

    
    @Column(name="Nazwa_Typu", nullable=false, length=50)
    public String getNazwaTypu() {
        return this.nazwaTypu;
    }
    
    public void setNazwaTypu(String nazwaTypu) {
        this.nazwaTypu = nazwaTypu;
    }

@OneToOne(fetch=FetchType.LAZY, mappedBy="producent")
    public Produkty getProdukty() {
        return this.produkty;
    }
    
    public void setProdukty(Produkty produkty) {
        this.produkty = produkty;
    }




}


