package data;
// Generated 2017-04-18 21:19:21 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Zamowienia generated by hbm2java
 */
@Entity
@Table(name="zamowienia"
    ,catalog="sklep"
)
public class Zamowienia  implements java.io.Serializable {


     private int idZamowienia;
     private Produkty produkty;
     private int idUzytkownika;
     private int idProduktu;
     private int cena;
     private int sztuk;
     private Uzytkownicy uzytkownicy;

    public Zamowienia() {
    }

	
    public Zamowienia(Produkty produkty, int idUzytkownika, int idProduktu, int cena, int sztuk) {
        this.produkty = produkty;
        this.idUzytkownika = idUzytkownika;
        this.idProduktu = idProduktu;
        this.cena = cena;
        this.sztuk = sztuk;
    }
    public Zamowienia(Produkty produkty, int idUzytkownika, int idProduktu, int cena, int sztuk, Uzytkownicy uzytkownicy) {
       this.produkty = produkty;
       this.idUzytkownika = idUzytkownika;
       this.idProduktu = idProduktu;
       this.cena = cena;
       this.sztuk = sztuk;
       this.uzytkownicy = uzytkownicy;
    }
   
     @GenericGenerator(name="generator", strategy="foreign", parameters=@Parameter(name="property", value="produkty"))@Id @GeneratedValue(generator="generator")

    
    @Column(name="Id_Zamowienia", unique=true, nullable=false)
    public int getIdZamowienia() {
        return this.idZamowienia;
    }
    
    public void setIdZamowienia(int idZamowienia) {
        this.idZamowienia = idZamowienia;
    }

@OneToOne(fetch=FetchType.LAZY)@PrimaryKeyJoinColumn
    public Produkty getProdukty() {
        return this.produkty;
    }
    
    public void setProdukty(Produkty produkty) {
        this.produkty = produkty;
    }

    
    @Column(name="Id_Uzytkownika", nullable=false)
    public int getIdUzytkownika() {
        return this.idUzytkownika;
    }
    
    public void setIdUzytkownika(int idUzytkownika) {
        this.idUzytkownika = idUzytkownika;
    }

    
    @Column(name="Id_Produktu", nullable=false)
    public int getIdProduktu() {
        return this.idProduktu;
    }
    
    public void setIdProduktu(int idProduktu) {
        this.idProduktu = idProduktu;
    }

    
    @Column(name="Cena", nullable=false)
    public int getCena() {
        return this.cena;
    }
    
    public void setCena(int cena) {
        this.cena = cena;
    }

    
    @Column(name="Sztuk", nullable=false)
    public int getSztuk() {
        return this.sztuk;
    }
    
    public void setSztuk(int sztuk) {
        this.sztuk = sztuk;
    }

@OneToOne(fetch=FetchType.LAZY, mappedBy="zamowienia")
    public Uzytkownicy getUzytkownicy() {
        return this.uzytkownicy;
    }
    
    public void setUzytkownicy(Uzytkownicy uzytkownicy) {
        this.uzytkownicy = uzytkownicy;
    }




}


