package data;
// Generated 2017-05-06 18:08:38 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Zamowienia generated by hbm2java
 */
@Entity
@Table(name="zamowienia"
    ,catalog="sklep"
)
public class Zamowienia  implements java.io.Serializable {


     private int idZamowienia;
     private Produkty produkty;
     private Uzytkownicy uzytkownicy;
     private int cena;
     private int sztuk;

    public Zamowienia() {
    }

    public Zamowienia(int idZamowienia, Produkty produkty, Uzytkownicy uzytkownicy, int cena, int sztuk) {
       this.idZamowienia = idZamowienia;
       this.produkty = produkty;
       this.uzytkownicy = uzytkownicy;
       this.cena = cena;
       this.sztuk = sztuk;
    }
   
     @Id 

    
    @Column(name="Id_Zamowienia", unique=true, nullable=false)
    public int getIdZamowienia() {
        return this.idZamowienia;
    }
    
    public void setIdZamowienia(int idZamowienia) {
        this.idZamowienia = idZamowienia;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Id_Produktu", nullable=false)
    public Produkty getProdukty() {
        return this.produkty;
    }
    
    public void setProdukty(Produkty produkty) {
        this.produkty = produkty;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Id_Uzytkownika", nullable=false)
    public Uzytkownicy getUzytkownicy() {
        return this.uzytkownicy;
    }
    
    public void setUzytkownicy(Uzytkownicy uzytkownicy) {
        this.uzytkownicy = uzytkownicy;
    }

    
    @Column(name="Cena", nullable=false)
    public int getCena() {
        return this.cena;
    }
    
    public void setCena(int cena) {
        this.cena = cena;
    }

    
    @Column(name="Sztuk", nullable=false)
    public int getSztuk() {
        return this.sztuk;
    }
    
    public void setSztuk(int sztuk) {
        this.sztuk = sztuk;
    }




}


